import React from 'react';
import SEO from '../components/SEO';
import { motion } from 'framer-motion';

const TermsPage = () => {
    return (
        <div className="min-h-screen bg-slate-50 pt-24 pb-16">
            <SEO title="Terms of Service" description="Terms and Conditions for Career Compass." />
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5 }}
                    className="bg-white rounded-2xl shadow-xl p-8 md:p-12 border border-slate-200"
                >
                    <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-8">Terms of Service</h1>

                    <div className="prose prose-slate max-w-none text-slate-600">
                        <p className="lead text-lg">
                            Last updated: {new Date().toLocaleDateString()}
                        </p>

                        <h3>1. Acceptance of Terms</h3>
                        <p>
                            By accessing or using Career Compass, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
                        </p>

                        <h3>2. Use License</h3>
                        <p>
                            Permission is granted to temporarily download one copy of the materials (information or software) on Career Compass for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.
                        </p>

                        <h3>3. Disclaimer</h3>
                        <p>
                            The materials on Career Compass are provided on an 'as is' basis. Career Compass makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
                        </p>

                        <h3>4. AI Analysis Disclaimer</h3>
                        <p>
                            Our resume analysis and career suggestions are generated by Artificial Intelligence. While we strive for accuracy, AI-generated content may occasionally be incorrect or misleading. You should verify any critical information and use your professional judgment when applying advice.
                        </p>

                        <h3>5. Limitations</h3>
                        <p>
                            In no event shall Career Compass or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Career Compass.
                        </p>
                    </div>
                </motion.div>
            </div>
        </div>
    );
};

export default TermsPage;
